### ISSUE TITLE
When copying attrs, only one should have the id

### ISSUE THREAD

**Issue by jimbojw** [arve0/markdown-it-header-sections#5]
Thanks for making this markdown-it plugin, working great!

My one issue is that when it copies attributes from the heading tag, it includes the `id` attribute. IDs should be unique within a page, so either the heading tag or the section tag should have the id, but not both.

**Comment by arve0** [comment]
Hi!
Thanks for reporting. You are correct, IDs should be unique.

**Comment by arve0** [comment]
Fixed in `v1.0.0`

**Comment by jimbojw** [comment]
Thanks for the quick fix!
